// Metal benchmark driver - initializes Lean runtime and calls benchmark
// This bypasses Lake's linking limitations with Metal frameworks

#include <lean/lean.h>
#include <stdio.h>

// Forward declarations for Lean-exported functions
// These are exported from TinyGrad4.Benchmark.MetalDirect
extern lean_obj_res lp_TinyGrad4_TinyGrad4_Benchmark_MetalDirect_testFFI(lean_obj_arg);
extern lean_obj_res lp_TinyGrad4_TinyGrad4_Benchmark_MetalDirect_runAll(lean_obj_arg);

// Initialize Lean modules (generated by Lake)
extern void initialize_TinyGrad4(uint8_t builtin, lean_object*);
extern void initialize_TinyGrad4_Benchmark_MetalDirect(uint8_t builtin, lean_object*);

int main(int argc, char** argv) {
    printf("TinyGrad4 Direct Metal Benchmark\n");
    printf("================================\n\n");

    // Initialize Lean runtime
    lean_initialize_runtime_module();
    lean_initialize();

    // Initialize our modules
    lean_obj_res init_res;

    // Initialize TinyGrad4 (and all dependencies)
    init_res = initialize_TinyGrad4(1, lean_io_mk_world());
    if (lean_io_result_is_error(init_res)) {
        fprintf(stderr, "Failed to initialize TinyGrad4\n");
        return 1;
    }
    lean_dec(init_res);

    // Initialize MetalDirect module
    init_res = initialize_TinyGrad4_Benchmark_MetalDirect(1, lean_io_mk_world());
    if (lean_io_result_is_error(init_res)) {
        fprintf(stderr, "Failed to initialize MetalDirect\n");
        return 1;
    }
    lean_dec(init_res);

    printf("Lean runtime initialized.\n\n");

    // Run FFI test
    printf("Running FFI test...\n");
    lean_obj_res test_res = lp_TinyGrad4_TinyGrad4_Benchmark_MetalDirect_testFFI(lean_io_mk_world());
    if (lean_io_result_is_error(test_res)) {
        fprintf(stderr, "FFI test failed\n");
        lean_dec(test_res);
        return 1;
    }
    lean_dec(test_res);

    printf("\nRunning benchmarks...\n");
    lean_obj_res bench_res = lp_TinyGrad4_TinyGrad4_Benchmark_MetalDirect_runAll(lean_io_mk_world());
    if (lean_io_result_is_error(bench_res)) {
        fprintf(stderr, "Benchmarks failed\n");
        lean_dec(bench_res);
        return 1;
    }

    // Get the result array
    lean_object* results = lean_io_result_get_value(bench_res);
    size_t num_results = lean_array_size(results);
    printf("\nCompleted %zu benchmarks\n", num_results);

    lean_dec(bench_res);

    printf("\nDone.\n");
    return 0;
}
